name: Feature Request
description: Request a new feature from pycontw-program-2024
title: "[Feature] "
labels: [new-feature]
body:
- type: markdown
  attributes:
    value: |
      Reference [apache/echarts](https://github.com/apache/echarts/tree/master/.github/ISSUE_TEMPLATE)

      The issue list is reserved exclusively for project management.

      Also try to search for your issue - it may have already been answered or even fixed in the other branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue using the form below instead of commenting on the old issue.

- type: textarea
  attributes:
    label: What problem does this feature solve?
    description: |
      Explain your use case, context, and rationale behind this feature request. More importantly, what is the end result you are trying to achieve that led to the need for this feature?

  validations:
    required: true

- type: textarea
  attributes:
    label: What does the proposed feature look like?
    description: Describe how you propose to solve the problem and provide code samples of how the feature would work once implemented. Note that you can use [Markdown](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format your code blocks.

  validations:
    required: true


- type: textarea
  attributes:
    label: Reference
    description: Any relevant links.

  validations:
    required: false